### ISSUE TITLE
How to pass `-XTypeApplications` to GHC?

### ISSUE THREAD

**Issue by s0kil** [haskell-actions/run-ormolu#1]
On my local installation, I could do:
```bash
HASKELL_FILES=$(find . -name '*.hs')

ormolu --mode inplace $HASKELL_FILES \
  --ghc-opt -XTypeApplications
```

How could I enable this on the GitHub Action, since it fails with:
```bash
  The GHC parser (in Haddock mode) failed:
  Pattern syntax in expression context:
    fromFrozenContext@(Maybe User)
Did you mean to enable TypeApplications?
```

**Comment by s0kil** [comment]
Maybe there is an `.ghc` config file, similar to `.ghci`?

**Comment by mrkkrp** [comment]
Use the `extra-args` parameter:

```yaml
      - uses: mrkkrp/ormolu-action@v1
        with:
          extra-args: --ghc-opt -XTypeApplications
```
