### ISSUE TITLE
Which files weren't formatted?

### ISSUE THREAD

**Issue by langston-barrett** [haskell-actions/run-ormolu#2]
I tried out this action and got the following error message:
```
Error: Ormolu detected unformatted files
```
I think it would be helpful to list which files were unformatted, so I can have an easier time of fixing the problem.

**Comment by mrkkrp** [comment]
Normally you'd get not only the file names but also the exact diffs of the changes that would be introduced by Ormolu in order to format the source code. Perhaps there is a bug. I'll take a look tomorrow.

**Comment by langston-barrett** [comment]
@mrkkrp Okay, thank you! Here's a run that had just that message: https://github.com/LuxMiranda/herms/runs/1758250412?check_suite_focus=true

**Comment by mrkkrp** [comment]
@langston-barrett What happens if you checkout the repo first?

```yaml
name: Format with Ormolu
on:
  - push
  - pull_request
jobs:
  linux:
    name: ormolu
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: mrkkrp/ormolu-action@v1
        with:
          pattern: |
            app/**/*.hs
            src/**/*.hs
            test/**/*.hs
```
